global:
  scrape_interval: 5s
  external_labels:
    monitor: 'golangsvc'

scrape_configs:
  - job_name: 'golangsvc'
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${IP}
        labels:
          version: ${VERSION}
  - job_name: 'postgresvc'
    scrape_interval: 5s
    static_configs:
      - targets: ${CONTAINERIP}