basePath: /
definitions:
  handler.request:
    properties:
      channel:
        type: string
      id:
        type: string
      metadata:
        additionalProperties: {}
        type: object
      payload:
        type: string
      timestamp:
        type: integer
    type: object
host: 127.0.0.1:80
info:
  contact: {}
  description: Afet Harita API
  title: IT Afet Yardım
  version: "1.0"
paths:
  /events:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create Event areas with request body
      tags:
      - Event
  /feeds/{id}:
    get:
      parameters:
      - description: Feed Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Feeds with given id
      tags:
      - Feed
  /feeds/areas:
    get:
      parameters:
      - description: Sw Lat
        in: query
        name: sw_lat
        required: true
        type: integer
      - description: Sw Lng
        in: query
        name: sw_lng
        required: true
        type: integer
      - description: Ne Lat
        in: query
        name: ne_lat
        required: true
        type: integer
      - description: Ne Lng
        in: query
        name: ne_lng
        required: true
        type: integer
      - description: Timestamp
        in: query
        name: time_stamp
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Feed areas with query strings
      tags:
      - Feed
  /healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show the status of server.
      tags:
      - Healthcheck
schemes:
- http
- https
swagger: "2.0"
